stages:
  stage_1:
    cmd: python topic_model.py
    deps:
      - topic_model.py
      - ../../../data/mtg.feather
    outs:
      - hw2_bert_model
  stage_2a:
    cmd: python multiclass.py 
    deps:
      - multiclass.py
      - ../../../data/mtg.feather
    outs:
      - multiclass_pipe.pkl
    params:
      - preprocessing.max_min_docs
    metrics:
      - metrics.json:
          cache: false
  stage_2b:
    cmd: python multilabel.py
    deps:
      - multilabel.py
      - ../../../data/mtg.feather
    outs:
      - multilabel_pipe.pkl
  stage_3:
    cmd: python rank_regression.py
    deps:
      - rank_regression.py
      - ../../../data/mtg.feather
    outs:
      - regression_GridSearch.pkl