stages:
  topic-model:
    cmd: python topic_model.py
    deps:
    - topic_model.py
  multiclass:
    cmd: python multiclass.py
    deps:
    - multiclass.py
    outs:
    - multiclass.sav
  multilabel:
    cmd: python multilabel.py
    deps:
    - multilabel.py
    outs:
    - multilabel.sav
  regression:
    cmd: python regression.py
    deps:
    - regression.py
 