stages:
  topic_model:
    cmd: python topic_model.py ../../../data/mtg.feather
    deps:
    - ../../../data/mtg.feather
    - topic_model.py
    outs:
    - my_model
  multiclass:
    cmd: python multiclass.py ../../../data/mtg.feather
    deps:
    - ../../../data/mtg.feather
    - multiclass.py
    outs:
    - mtg_classifier.pkl
  multilabel:
    cmd: python multilabel.py ../../../data/mtg.feather
    deps:
    - ../../../data/mtg.feather
    - multilabel.py
    outs:
    - mtg_classifier_multilabel.pkl
  regression:
    cmd: python regression.py ../../../data/mtg.feather
    deps:
    - ../../../data/mtg.feather
    - regression.py
    outs:
    - regression.pkl
